### ISSUE TITLE
Module build failed: Error: Non-whitespace before first tag.

### ISSUE THREAD

**Issue by ccorcos** [jhamlet/svg-react-loader#19]
```
Module build failed: Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: m
    at error (/Users/chetcorcos/code/frog/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/Users/chetcorcos/code/frog/node_modules/sax/lib/sax.js:693:7)
    at beginWhiteSpace (/Users/chetcorcos/code/frog/node_modules/sax/lib/sax.js:967:7)
    at Object.write (/Users/chetcorcos/code/frog/node_modules/sax/lib/sax.js:1019:11)
    at Parser.exports.Parser.Parser.parseString (/Users/chetcorcos/code/frog/node_modules/xml2js/lib/xml2js.js:503:31)
    at Parser.parseString (/Users/chetcorcos/code/frog/node_modules/xml2js/lib/xml2js.js:7:59)
    at parseXml (/Users/chetcorcos/code/frog/node_modules/svg-react-loader/index.js:23:15)
    at wrapper (/Users/chetcorcos/code/frog/node_modules/svg-react-loader/node_modules/lodash/internal/createPartialWrapper.js:38:15)
    at /Users/chetcorcos/code/frog/node_modules/svg-react-loader/index.js:92:9
    at /Users/chetcorcos/code/frog/node_modules/svg-react-loader/index.js:17:9
 @ ./src/ui/nav/index.js 13:12-37
webpack: bundle is now VALID.
```

here's the svg:

```
<svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><style>.st0{fill:#3AC98D;}</style><path d="M20 0C9 0 0 9 0 20s9 20 20 20 20-9 20-20S31 0 20 0zm2.7 26.3V16.1l-7.1 9-.1.2c-.5.6-1.3 1-2.1 1H10l1-1.2 3.4-4.3 7.4-9.3c.5-.7 1.4-1.1 2.4-1 1.4.2 2.4 1.3 2.4 2.7v13.2h-3.9z"/></svg>
```

**Comment by udovenko** [comment]
Yes, have the same issue...
Module build failed: Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: m
 at error (/home/denis/web-projects/tekoa/webpack/node_modules/sax/lib/sax.js:666:10)
at strictFail (/home/denis/web-projects/tekoa/webpack/node_modules/sax/lib/sax.js:692:7)
at beginWhiteSpace (/home/denis/web-projects/tekoa/webpack/node_modules/sax/lib/sax.js:965:7)
at Object.write (/home/denis/web-projects/tekoa/webpack/node_modules/sax/lib/sax.js:1017:11)
at Parser.exports.Parser.Parser.parseString (/home/denis/web-projects/tekoa/webpack/node_modules/xml2js/lib/xml2js.js:503:31)
at Parser.parseString (/home/denis/web-projects/tekoa/webpack/node_modules/xml2js/lib/xml2js.js:7:59)
at parseXml (/home/denis/web-projects/tekoa/webpack/node_modules/svg-react-loader/index.js:23:15)
at wrapper (/home/denis/web-projects/tekoa/webpack/node_modules/svg-react-loader/node_modules/lodash/internal/createPartialWrapper.js:38:15)
at /home/denis/web-projects/tekoa/webpack/node_modules/svg-react-loader/index.js:92:9
at /home/denis/web-projects/tekoa/webpack/node_modules/svg-react-loader/index.js:17:9
@ ./app/assets/javascripts/components/layout/Header.jsx 17:18-66

**Comment by ccorcos** [comment]
https://github.com/jhamlet/svg-react-loader/issues/3

**Comment by ccorcos** [comment]
I ran into this 6 months ago apparently ;)

**Comment by udovenko** [comment]
Oh, sorry. Overlook...)

**Comment by saharNofal** [comment]
try to remove platforms and rebuild

**Comment by imjasonmiller** [comment]
I ran into this exact error as well, but caused it by omitting an [`include`](https://webpack.js.org/configuration/module/#rule-conditions) for my font loader, which allowed it to pick up other `.svg` files.
