### ISSUE TITLE
Cannot Find Module

### ISSUE THREAD

**Issue by esparkman** [jhamlet/svg-react-loader#51]
React 15.4.1
Babel 6.7.4

I am getting this error when trying to use svg-react-loader.
```
Cannot find module 'babel!svg-react!./assets/MMRBlueLogo.svg?name=MMRBlueLogo'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/evansparkman/Development/emmr-frontend/src/containers/Heading/index.js:19:21)
    at Module._compile (module.js:573:32)
    at loader (/Users/evansparkman/Development/emmr-frontend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/evansparkman/Development/emmr-frontend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/evansparkman/Development/emmr-frontend/src/app.js:16:1)
    at Module._compile (module.js:573:32)
    at loader (/Users/evansparkman/Development/emmr-frontend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/evansparkman/Development/emmr-frontend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.prerenderApp (/Users/evansparkman/Development/emmr-frontend/lib/webpack/plugins/PrecompileTemplatesPlugin.js:77:15)
    at eval (eval at compile (/Users/evansparkman/Development/emmr-frontend/node_modules/ejs/lib/ejs.js:498:12), <anonymous>:38:16)
    at returnedFn (/Users/evansparkman/Development/emmr-frontend/node_modules/ejs/lib/ejs.js:529:17)
    at Object.exports.render (/Users/evansparkman/Development/emmr-frontend/node_modules/ejs/lib/ejs.js:339:37)
    at Compiler.compiler.plugin (/Users/evansparkman/Development/emmr-frontend/lib/webpack/plugins/PrecompileTemplatesPlugin.js:40:26)
    at Compiler.next (/Users/evansparkman/Development/emmr-frontend/node_modules/tapable/lib/Tapable.js:69:14)
    at callback (/Users/evansparkman/Development/emmr-frontend/node_modules/copy-webpack-plugin/dist/index.js:71:17)
    at Object.finallyHandler (/Users/evansparkman/Development/emmr-frontend/node_modules/bluebird/js/main/finally.js:39:23)
```
My webpack.config.js looks like the below.
```
module: {
    loaders: [
      {
        test: /\.svg$/,
        loader: 'babel?presets[]=es2015,presets[]=react!svg-react'
      },
      {
        loader: 'babel-loader',
        test: /\.js$/,
        exclude: /node_modules/
      },
      .........
```
My package.json(Deps/DevDeps).
```
"dependencies": {
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.8",
    "babel-polyfill": "6.16.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "custom-event": "1.0.1",
    "deep-equal": "1.0.1",
    "history": "3.2.1",
    "jquery": "3.1.1",
    "lodash": "4.17.2",
    "react": "https://registry.npmjs.org/react/-/react-15.4.1.tgz",
    "react-dom": "https://registry.npmjs.org/react-dom/-/react-dom-15.4.1.tgz",
    "react-onclickoutside": "5.7.1",
    "react-redux": "4.4.6",
    "react-select": "1.0.0-rc.2",
    "redux": "3.6.0",
    "redux-devtools-extension": "1.0.0",
    "redux-logger": "2.7.4",
    "redux-saga": "0.13.0",
    "superagent": "3.1.0",
    "svg-react-loader": "^0.4.0-beta.2"
  },
  "devDependencies": {
    "babel-core": "^6.7.4",
    "babel-eslint": "^5.0.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-lodash": "^3.2.10",
    "babel-plugin-module-resolver": "^2.3.0",
    "babel-plugin-react-remove-properties": "^0.2.3",
    "babel-plugin-react-require": "^3.0.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
    "body-parser": "^1.15.2",
    "chalk": "^1.1.1",
    "chokidar-cli": "^1.2.0",
    "copy-webpack-plugin": "^4.0.1",
    "cors": "^2.7.1",
    "css-loader": "^0.23.1",
    "css-modules-require-hook": "^4.0.0",
    "ejs": "^2.4.1",
    "enzyme": "^2.3.0",
    "eslint": "1.x",
    "eslint-config-airbnb": "^5.0.1",
    "eslint-plugin-babel": "^3.1.0",
    "eslint-plugin-react": "^3.16.1",
    "expose-loader": "^0.7.1",
    "express": "^4.13.4",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "images-require-hook": "^1.0.3",
    "jsdom": "^9.8.3",
    "json-loader": "^0.5.4",
    "live-server": "^1.1.0",
    "node-sass": "^3.4.2",
    "npm-run-all": "^3.1.1",
    "nyc": "^10.0.0",
    "progress-bar-webpack-plugin": "^1.9.0",
    "react-addons-test-utils": "15.4.1",
    "sass-loader": "^4.0.2",
    "sinon": "^1.17.4",
    "style-loader": "^0.13.0",
    "tap-dot": "^1.0.5",
    "tap-summary": "^3.0.1",
    "tape": "^4.4.0",
    "tape-catch": "^1.0.5",
    "tape-scenario": "^0.2.3",
    "webpack": "^1.12.14",
    "webpack-cleanup-plugin": "^0.4.1",
    "webpack-livereload-plugin": "^0.9.0"
  },
```

**Comment by cliener** [comment]
From the [0.4.0 beta notes](https://github.com/jhamlet/svg-react-loader/blob/version-0.4.0/README.md):

> As of version 0.4.0, svg-react-loader no longer requires babel to transpile the generated code. Everything is returned as an ES5-7 compatible module, and the component is just a function. With that, it only works with React@>=0.14
