### ISSUE TITLE
Error loading SVG with -- (two consecutive dashes) in the name

### ISSUE THREAD

**Issue by cupojoe** [jhamlet/svg-react-loader#93]
This is the error from the Gatsby build:

`
Module build failed: TypeError: Cannot read property 'toUpperCase' of undefined
    at upperCaseFirst (/node_modules/svg-react-loader/lib/util/upper-case-first.js:2:19)
    at Array.map (<anonymous>)
    at titleCase (/node_modules/svg-react-loader/lib/util/title-case.js:10:9)
    at /node_modules/svg-react-loader/node_modules/ramda/dist/ramda.js:551:35
    at /node_modules/svg-react-loader/node_modules/ramda/dist/ramda.js:48:27
    at titleCaseBasename (/node_modules/svg-react-loader/lib/loader.js:10:28)
    at Object.svgReactLoader (/node_modules/svg-react-loader/lib/loader.js:29:41)
 @ ./src/components/Nav.js 44:22-72
`

Changing the name to one dash fixes the issue, but unfortunately this is using a third party library of icons, probably won't be able to change it.

**Comment by cupojoe** [comment]
@jhamlet do you have any idea what could be causing this?

**Comment by jhamlet** [comment]
Fixed with your pull request?

**Comment by cupojoe** [comment]
@jhamlet yeah, that PR fixes it. Thank you!
